name: "Hello world github actions"
    
on: 
  push:
    branches:
      - main
      - production
      - master

jobs: 
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: "show date"
        run: date
        

