name: "multi pipleine"

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
      - master

jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: "demo"
        run: echo "demo done"
